# Generated by Django 5.1.4 on 2025-03-14 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_section', '0001_initial'),
        ('concourse', '0004_concourseresource_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcourPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image_post', models.ImageField(blank=True, null=True, upload_to='chat_section/concour_post')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('concourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concour_posts', to='concourse.concourse')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concour_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
