# Generated by Django 5.1.2 on 2024-11-08 01:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concourse',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concourse',
            name='exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concourse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='concoursedepartment',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='latestnews',
            name='concourse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latestNews', to='concourse.concourse'),
        ),
        migrations.AddField(
            model_name='latestnews',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='latestnews',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='latestnews',
            name='newsDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ConcourseQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('concourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='concourse.concourse')),
            ],
        ),
        migrations.CreateModel(
            name='ConcourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('url', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('concourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='concourse.concourse')),
            ],
        ),
    ]
