# Generated by Django 5.1.2 on 2024-11-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concourse',
            old_name='concourseTypeField',
            new_name='concourseType',
        ),
    ]
