# Generated by Django 5.1.2 on 2024-11-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concourse', '0002_rename_concoursetypefield_concourse_concoursetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='pdf',
            field=models.FileField(default='images/latestNews/frame.png', upload_to='images/latestNews/'),
            preserve_default=False,
        ),
    ]
