# Generated by Django 5.1.2 on 2024-11-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concourse', '0002_concourse_application_deadline_concourse_exam_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concourse',
            name='schoolPicture',
            field=models.ImageField(blank=True, null=True, upload_to='concourse/images'),
        ),
    ]
