# Generated by Django 5.1.2 on 2024-11-08 04:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concourse', '0003_concourse_schoolpicture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='concourse/latestNews/'),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='newsDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ConcourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('concourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concourse', to='concourse.concourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concourseUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'concourse')},
            },
        ),
    ]
