# Generated by Django 5.1.2 on 2024-11-08 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concourse', '0004_latestnews_pdf_alter_latestnews_newsdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='concourse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='latestNews', to='concourse.concourse'),
            preserve_default=False,
        ),
    ]
