# Generated by Django 5.1.2 on 2024-11-28 02:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concourse', '0005_rename_concourseapplication_concourseregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='concourseregistration',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='concourseregistration',
            name='phoneNumber',
            field=models.CharField(default=234958, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered as digits only and must be between 7 and 10 digits.', regex='^\\d{7,10}$')]),
            preserve_default=False,
        ),
    ]
