# Generated by Django 5.1.4 on 2025-02-10 18:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcourseTypeField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concourseTypeField', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concourseName', models.CharField(max_length=100)),
                ('concourseSubName', models.CharField(blank=True, max_length=100, null=True)),
                ('activeUsers', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('schoolPicture', models.ImageField(blank=True, null=True, upload_to='concourse/images')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('concourseType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concourses', to='concourse.concoursetypefield')),
            ],
        ),
        migrations.CreateModel(
            name='ConcourseDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('departmentConcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='concourse.concourse')),
            ],
        ),
        migrations.CreateModel(
            name='ConcourseQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('concourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='concourse.concourse')),
            ],
        ),
        migrations.CreateModel(
            name='ConcourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('url', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('concourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='concourse.concourse')),
            ],
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('newsDate', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('pdf', models.FileField(upload_to='images/latestNews/')),
                ('is_published', models.BooleanField(default=True)),
                ('concourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latestNews', to='concourse.concourse')),
            ],
        ),
        migrations.CreateModel(
            name='ConcourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('phoneNumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be entered as digits only and must be between 7 and 10 digits.', regex='^\\d{7,10}$')])),
                ('concourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concourse', to='concourse.concourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concourseUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'concourse')},
            },
        ),
    ]
