# Generated by Django 5.1.4 on 2025-02-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concourseregistration',
            name='payment_service',
            field=models.CharField(default='MTN', max_length=20),
        ),
    ]