# Generated by Django 5.1.4 on 2025-02-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concourse', '0002_concourseregistration_payment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='concourseresource',
            name='category',
            field=models.CharField(choices=[('document', 'Document'), ('link', 'Link'), ('lab_session', 'Lab Session'), ('paper', 'Paper')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]