# Generated by Django 5.1.4 on 2025-02-27 06:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concourse', '0003_concourseresource_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='concourseresource',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
