# Generated by Django 5.1.2 on 2024-11-16 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concourse', '0003_alter_latestnews_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestnews',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
