# Generated by Django 5.1.2 on 2024-11-25 13:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concourse', '0004_alter_latestnews_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConcourseApplication',
            new_name='ConcourseRegistration',
        ),
    ]
