# Generated by Django 5.1.4 on 2025-03-16 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concourse', '0004_concourseresource_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcourseSolutionGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='concourse/solution_guides/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField()),
                ('concourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_guides', to='concourse.concourse')),
            ],
        ),
    ]
