# Generated by Django 5.1.4 on 2025-01-18 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concourse', '0006_concourseregistration_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='concourseUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concourseUniversity', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='concourse',
            name='concourseUni',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='concourseSchool', to='concourse.concourseuniversity'),
            preserve_default=False,
        ),
    ]
