# Generated by Django 5.1.4 on 2025-05-09 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concourse", "0006_alter_concoursequiz_concourse_quiz_question_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="concourseregistration",
            name="referrer",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who referred this registration.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
