# Generated by Django 5.1.4 on 2025-02-13 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concourse', '0006_concourseregistration_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcoursePastPapers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='concourse/past_papers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('year', models.IntegerField()),
                ('concourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_papers', to='concourse.concourse')),
            ],
        ),
    ]
