# Generated by Django 5.1.4 on 2025-05-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concourse", "0007_concourseregistration_referrer"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bonus_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Percentage bonus to be awarded to the referrer based on the concourse price.",
                        max_digits=5,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="concourse",
            name="bonus_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Bonus value to be awarded to the referrer for this concourse.",
                max_digits=10,
            ),
        ),
    ]
