# Generated by Django 5.1.4 on 2025-06-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concourse", "0009_withdrawal"),
    ]

    operations = [
        migrations.AddField(
            model_name="globalsettings",
            name="video_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="video_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="globalsettings",
            name="video_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
