# Generated by Django 5.1.4 on 2025-08-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concourse', '0010_globalsettings_video_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concoursepastpapers',
            name='concourse',
        ),
        migrations.RemoveField(
            model_name='concoursequiz',
            name='concourse',
        ),
        migrations.RemoveField(
            model_name='concourseresource',
            name='concourse',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='concourse',
        ),
        migrations.AddField(
            model_name='concoursepastpapers',
            name='concourse',
            field=models.ManyToManyField(related_name='past_papers', to='concourse.concourse'),
        ),
        migrations.AddField(
            model_name='concoursequiz',
            name='concourse',
            field=models.ManyToManyField(related_name='concourse_quizzes', to='concourse.concourse'),
        ),
        migrations.AddField(
            model_name='concourseresource',
            name='concourse',
            field=models.ManyToManyField(related_name='resources', to='concourse.concourse'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='concourse',
            field=models.ManyToManyField(related_name='quizzes', to='concourse.concourse'),
        ),
    ]
