# Generated by Django 5.1.2 on 2024-11-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoucement_news', '0003_notification_delete_annoucement'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
