# Generated by Django 5.1.2 on 2024-10-31 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='post_user',
        ),
    ]
