# Generated by Django 5.1.4 on 2025-04-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoucement_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageToStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
