# Generated by Django 5.1.4 on 2025-05-17 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annoucement_news', '0003_device_pushnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushnotification',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='pushnotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='PushNotification',
        ),
    ]
