# Generated by Django 5.1.4 on 2025-06-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annoucement_news', '0004_remove_pushnotification_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
    ]
