# Generated by Django 5.1.4 on 2025-03-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='whatsapp_number',
            field=models.CharField(default=681775574, max_length=15),
            preserve_default=False,
        ),
    ]
