# Generated by Django 5.1.4 on 2025-05-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bonus_balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Referral bonus balance",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="referral_code",
            field=models.CharField(
                blank=True,
                help_text="WhatsApp number of the referrer (optional)",
                max_length=20,
                null=True,
            ),
        ),
    ]
