# Generated by Django 5.1.4 on 2025-03-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
