# Generated by Django 5.1.4 on 2025-03-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_customuser_whatsapp_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="whatsapp_number",
            field=models.CharField(default=681775574, max_length=15),
            preserve_default=False,
        ),
    ]
