# Generated by Django 5.1.4 on 2025-05-17 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_bonus_balance_customuser_referral_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.OneToOneField(help_text='The user who was referred.', on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(help_text='The user who referred others.', on_delete=django.db.models.deletion.CASCADE, related_name='referral_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
