# Generated by Django 5.1.4 on 2025-03-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_customuser_whatsapp_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
